# Generated by Django 5.2.4 on 2025-07-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('major', models.CharField(max_length=100)),
                ('gpa', models.FloatField()),
                ('enrollment_date', models.DateField()),
            ],
            options={
                'db_table': 'student_records',
            },
        ),
    ]
